# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: netmap.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'netmap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnetmap.proto\x12\x06netmap\"*\n\x12NetworkDataRequest\x12\x14\n\x0cnetwork_data\x18\x01 \x01(\t\"&\n\x13NetworkDataResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2T\n\x06NetMap\x12J\n\x0fSendNetworkData\x12\x1a.netmap.NetworkDataRequest\x1a\x1b.netmap.NetworkDataResponseB\x0fZ\r./proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'netmap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./proto;proto'
  _globals['_NETWORKDATAREQUEST']._serialized_start=24
  _globals['_NETWORKDATAREQUEST']._serialized_end=66
  _globals['_NETWORKDATARESPONSE']._serialized_start=68
  _globals['_NETWORKDATARESPONSE']._serialized_end=106
  _globals['_NETMAP']._serialized_start=108
  _globals['_NETMAP']._serialized_end=192
# @@protoc_insertion_point(module_scope)
