// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: netmap.proto

package netmap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetMap_GetState_FullMethodName         = "/netmap.NetMap/GetState"
	NetMap_SubscribeUpdates_FullMethodName = "/netmap.NetMap/SubscribeUpdates"
)

// NetMapClient is the client API for NetMap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetMapClient interface {
	GetState(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	SubscribeUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type netMapClient struct {
	cc grpc.ClientConnInterface
}

func NewNetMapClient(cc grpc.ClientConnInterface) NetMapClient {
	return &netMapClient{cc}
}

func (c *netMapClient) GetState(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, NetMap_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netMapClient) SubscribeUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetMap_ServiceDesc.Streams[0], NetMap_SubscribeUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetMap_SubscribeUpdatesClient = grpc.BidiStreamingClient[Request, Response]

// NetMapServer is the server API for NetMap service.
// All implementations must embed UnimplementedNetMapServer
// for forward compatibility.
type NetMapServer interface {
	GetState(context.Context, *Request) (*Response, error)
	SubscribeUpdates(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedNetMapServer()
}

// UnimplementedNetMapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetMapServer struct{}

func (UnimplementedNetMapServer) GetState(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedNetMapServer) SubscribeUpdates(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeUpdates not implemented")
}
func (UnimplementedNetMapServer) mustEmbedUnimplementedNetMapServer() {}
func (UnimplementedNetMapServer) testEmbeddedByValue()                {}

// UnsafeNetMapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetMapServer will
// result in compilation errors.
type UnsafeNetMapServer interface {
	mustEmbedUnimplementedNetMapServer()
}

func RegisterNetMapServer(s grpc.ServiceRegistrar, srv NetMapServer) {
	// If the following call pancis, it indicates UnimplementedNetMapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetMap_ServiceDesc, srv)
}

func _NetMap_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetMapServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetMap_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetMapServer).GetState(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetMap_SubscribeUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetMapServer).SubscribeUpdates(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetMap_SubscribeUpdatesServer = grpc.BidiStreamingServer[Request, Response]

// NetMap_ServiceDesc is the grpc.ServiceDesc for NetMap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetMap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmap.NetMap",
	HandlerType: (*NetMapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _NetMap_GetState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeUpdates",
			Handler:       _NetMap_SubscribeUpdates_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "netmap.proto",
}
