// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/netmap.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetMap_SendNetworkData_FullMethodName = "/netmap.NetMap/SendNetworkData"
)

// NetMapClient is the client API for NetMap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the service
type NetMapClient interface {
	SendNetworkData(ctx context.Context, in *NetworkDataRequest, opts ...grpc.CallOption) (*NetworkDataResponse, error)
}

type netMapClient struct {
	cc grpc.ClientConnInterface
}

func NewNetMapClient(cc grpc.ClientConnInterface) NetMapClient {
	return &netMapClient{cc}
}

func (c *netMapClient) SendNetworkData(ctx context.Context, in *NetworkDataRequest, opts ...grpc.CallOption) (*NetworkDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkDataResponse)
	err := c.cc.Invoke(ctx, NetMap_SendNetworkData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetMapServer is the server API for NetMap service.
// All implementations must embed UnimplementedNetMapServer
// for forward compatibility.
//
// Define the service
type NetMapServer interface {
	SendNetworkData(context.Context, *NetworkDataRequest) (*NetworkDataResponse, error)
	mustEmbedUnimplementedNetMapServer()
}

// UnimplementedNetMapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetMapServer struct{}

func (UnimplementedNetMapServer) SendNetworkData(context.Context, *NetworkDataRequest) (*NetworkDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNetworkData not implemented")
}
func (UnimplementedNetMapServer) mustEmbedUnimplementedNetMapServer() {}
func (UnimplementedNetMapServer) testEmbeddedByValue()                {}

// UnsafeNetMapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetMapServer will
// result in compilation errors.
type UnsafeNetMapServer interface {
	mustEmbedUnimplementedNetMapServer()
}

func RegisterNetMapServer(s grpc.ServiceRegistrar, srv NetMapServer) {
	// If the following call pancis, it indicates UnimplementedNetMapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetMap_ServiceDesc, srv)
}

func _NetMap_SendNetworkData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetMapServer).SendNetworkData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetMap_SendNetworkData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetMapServer).SendNetworkData(ctx, req.(*NetworkDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetMap_ServiceDesc is the grpc.ServiceDesc for NetMap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetMap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmap.NetMap",
	HandlerType: (*NetMapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNetworkData",
			Handler:    _NetMap_SendNetworkData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/netmap.proto",
}
